

#development:
#  adapter: postgresql
#  host: localhost
#  username: postgres
#  database: midapt
#  password: 308317
#  port: 5432

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

cucumber:
  <<: *test